-- MySQL Script generated by MySQL Workbench
-- Thu Mar 24 11:00:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecodev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecodev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecodev` DEFAULT CHARACTER SET utf8 ;
USE `ecodev` ;

-- -----------------------------------------------------
-- Table `ecodev`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecodev`.`users` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) UNIQUE NOT NULL,
  `phone` VARCHAR(25),
  `country` VARCHAR(80),
  `province` VARCHAR(80),
  `address` VARCHAR(50),
  `password` VARCHAR(50) NOT NULL,
  `avatar` VARCHAR(100));
  
-- -----------------------------------------------------
-- Table `ecodev`.`categories`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `ecodev`.`categories` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL
  );
  
  -- -----------------------------------------------------
-- Table `ecodev`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecodev`.`products` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(11,2) NULL,
  `image` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `categories_id` INT NOT NULL,
  `insale` INT,
  `off` INT, 
  `highlight` INT, 
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `ecodev`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  );

-- -----------------------------------------------------
-- Table `ecodev`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecodev`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(11,2) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),  
  CONSTRAINT `fk_carts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecodev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `ecodev`.`carts_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecodev`.`carts_has_products` (
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`cart_id`, `product_id`),
  INDEX `fk_carts_has_products_products1_idx` (`product_id` ASC),
  INDEX `fk_carts_has_products_carts1_idx` (`cart_id` ASC),
  CONSTRAINT `fk_carts_has_products_carts1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `ecodev`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecodev`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `ecodev`.`user_favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecodev`.`user_favorites` (
  `products_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `users_id`),
  INDEX `fk_products_has_users_users1_idx` (`users_id` ASC),
  INDEX `fk_products_has_users_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_products_has_users_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `ecodev`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ecodev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `ecodev`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecodev`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order` INT NULL,
  `date` DATETIME NULL,
  `carts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `carts_id`),
  UNIQUE INDEX `order_UNIQUE` (`order` ASC),
  INDEX `fk_sales_carts1_idx` (`carts_id` ASC),
  CONSTRAINT `fk_sales_carts1`
    FOREIGN KEY (`carts_id`)
    REFERENCES `ecodev`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
